"use client";

import { useQuery } from "@tanstack/react-query";
import { ScrollText } from "lucide-react";
import { listTailoredAssets } from "@/services/retrieval";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { formatDate } from "@/lib/utils";

export const TailoredAssetsCard = () => {
  const query = useQuery({
    queryKey: ["tailored-assets"],
    queryFn: () => listTailoredAssets(),
  });

  const assets = query.data ?? [];

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <ScrollText className="h-5 w-5 text-primary" />
          Tailored assets
        </CardTitle>
        <CardDescription>Recent cover letters & resume packs generated by the AI adapter.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        {query.isLoading && <Skeleton className="h-20 w-full" />}
        {!query.isLoading && assets.length === 0 && (
          <p className="text-sm text-muted-foreground">Generate a cover letter to see it here.</p>
        )}
        {assets.slice(0, 3).map((asset) => (
          <div key={asset.id} className="rounded-xl border border-border/60 p-3">
            <p className="text-sm font-semibold">
              {asset.jobTitle} / {asset.assetType.replace("_", " ")}
            </p>
            <p className="text-xs text-muted-foreground">{formatDate(asset.updatedAt)}</p>
          </div>
        ))}
      </CardContent>
    </Card>
  );
};
